version: 2

language:
  file_name: zh_cn # 语言文件名 **.yml 语言文件存储于lang文件夹下面

bStats:
  enable: true  # 开启bStats

here:
  enable: true  # 是否允许使用here
  permission:
    self: # here对象为玩家自己
      enable: false  # 是否开启此项的权限管理
      node: points.command.here
  voxelmap-support: false  # 是否开启Voxelmap支持
  xaeros-support: false  # 是否开启Xaeros支持
  teleport-support: false  # 是否开启tp支持
  glowing:
    enable: true  # 是否高亮
    time: 20  # 高亮时间，单位 秒

where:
  enable: true  # 是否允许使用where
  permission:
    self: # where对象为玩家自己
      enable: false  # 是否开启此项的权限管理
      node: points.command.where.self
    other: # where对象为其他玩家
      enable: true  # 是否开启此项的权限管理
      node-other-player: points.command.where.other  # 其他玩家
      node-target-player: points.command.where.other.%s  # 指定玩家 %s为玩家名的占位符
  voxelmap-support: false  # 是否开启Voxelmap支持
  xaeros-support: false  # 是否开启Xaeros支持
  teleport-support: false  # 是否开启tp支持

death:
  enable: true  # 是否启用death子模块
  storage:
    db-type: sqlite # 存储方式 -> [sqlite] 没有其他选择
  message:
    # 当你死亡的时候会向你发送死亡地点等信息
    enable: true  # 是否启用death message子模块
    command-permission: # /death message 指令权限
      enable: false  # 是否开启权限管理
      node: points.command.death.message  # 权限节点
    listener-permission: # 监听器权限
      enable: false  # 是否开启权限管理 开启权限管理后，依然可以使用指令，如无对应权限，死亡将不会发送消息
      node: points.listener.death.message  # 权限节点
    voxelmap-support: false  # 是否开启Voxelmap支持
    xaeros-support: false  # 是否开启Xaeros支持
    teleport-support: false  # 是否开启tp支持

  log:
    # 记录死亡信息
    enable: true  # 是否启用death log子模块
    permission:
      self: # death log对象为玩家自己
        enable: false  # 是否开启此项的权限管理
        node: points.command.death.log.self
      other: # death log对象为其他玩家
        enable: true  # 是否开启此项的权限管理
        node-other-player: points.command.death.log.other  # 其他玩家
        node-target-player: points.command.death.log.other.%s  # 指定玩家 %s为玩家名的占位符
    command:
      frequency-limit:
        enable: true  # 是否限制玩家使用 death log 指令频率
        # 每几秒 允许查询几次
        second: 1  # 每n秒
        maximum-usage: 1 # 允许查询n次
    record-limit: 5  # 死亡记录上限
    voxelmap-support: false  # 是否开启Voxelmap支持
    xaeros-support: false  # 是否开启Xaeros支持
    teleport-support: false  # 是否开启tp支持

enderchest:
  # 随身末影箱
  enable: true  # 是否启用enderchest随身末影箱
  permission:
    self:  # enderchest对象为玩家自己
      enable: false  # 是否开启此项的权限管理
      node: points.command.enderchest.self
    other: # enderchest对象为其他玩家
      enable: true  # 是否开启此项的权限管理
      node-other-player: points.command.enderchest.other  # 其他玩家
      node-target-player: points.command.enderchest.other.%s  # 指定玩家 %s为玩家名的占位符

anti-boom:
  # 防爆
  enable: true  # 是否启用anti-boom子模块
  # enable 是否启用子模块
  # world是主世界是否启用 world-nether是下界是否启用 world-the-end是末地是否启用
  world-name: # 世界名字，一般无需修改
    world: world
    world-nether: world_nether
    world-the-end: world_the_end
  bed:
    enable: false  # 防止下界和末地床爆炸, 本质上是阻止玩家使用床
    world: false
    world-nether: false
    world-the-end: false
  creeper:
    enable: false  # 防止苦力怕爆炸
    world: false
    world-nether: false
    world-the-end: false
  ender-crystal:
    enable: false  # 防止末影水晶爆炸
    world: false
    world-nether: false
    world-the-end: false
  ghast:
    enable: false  # 防止恶魂火球爆炸
    world: false
    world-nether: false
    world-the-end: false
  minecart-tnt:
    enable: false  # 防止tnt矿车爆炸
    world: false
    world-nether: false
    world-the-end: false
  respawn-anchor:
    enable: false  # 防止重生锚爆炸, 本质上是阻止玩家使用重生锚
    world: false
    world-nether: false
    world-the-end: false
  tnt:
    enable: false  # 防止tnt爆炸
    world: false
    world-nether: false
    world-the-end: false
  wither:
    skull:
      enable: false  # 凋零发射的头颅
      world: false
      world-nether: false
      world-the-end: false
    spawn:
      enable: false  # 凋零生成的时候爆炸
      world: false
      world-nether: false
      world-the-end: false
    body:
      enable: false  # 凋零自身破坏方块
      world: false
      world-nether: false
      world-the-end: false

points:
  reload:
    permission:
      enable: true  # 是否开启权限管理
      node: points.reload  # 权限节点

debug:  # debug模式
  enable: false

log:  # 详细信息
  more-information: false