version: 1

here:
  enable: true  # 是否允许使用here
  permission: false  # 是否开启权限管理
  voxelmap-support: false  # 是否开启Voxelmap支持
  xaeros-support: false  # 是否开启Xaeros支持
  teleport-support: false  # 是否开启tp支持
  glowing:
    enable: true  # 是否高亮
    time: 20  # 高亮时间，单位 秒

where:
  enable: true  # 是否允许使用where
  permission: false  # 是否开启权限管理
  voxelmap-support: false  # 是否开启Voxelmap支持
  xaeros-support: false  # 是否开启Xaeros支持
  teleport-support: false  # 是否开启tp支持

death:
  enable: true  # 是否启用death子模块
  message:
    # 当你死亡的时候会向你发送死亡地点等信息
    enable: true  # 是否启用death message子模块
    permission: false  # 是否开启权限管理
    voxelmap-support: false  # 是否开启Voxelmap支持
    xaeros-support: false  # 是否开启Xaeros支持
    teleport-support: false  # 是否开启tp支持

  log:
    # 记录死亡信息
    enable: true  # 是否启用death log子模块
    permission: false  # 是否开启权限管理
    limit: 5  # 死亡记录上限
    storage: sqlite  # 存储方式 storage -> [sqlite] 没有其他选择