name: Points
version: '0.2.3'
main: com.hzzz.points.Points
api-version: 1.17
authors: [ Hzzz ]
description: Some useful points
commands:
  where:
    description: Get player position
    aliases: [ whe, wh ]
    usage: "Not enable 'where'"
  here:
    description: Broadcast player position
    aliases: [ he ]
    usage: "Not enable 'here'"
  death:
    description: About death
    aliases: [ de ]
    usage: "Not enable 'death'"
  enderchest:
    description: About enderchest
    aliases: [ ec ]
    usage: "Not enable 'enderchest'"
  points:
    description: plugin commands
    aliases: [ po ]
    usage: "Not enable 'points'"